services:
  bot:
    build: .
    environment:
      - MONGODB_CONNSTRING=mongodb://db:27017
    env_file: .env
    container_name: timezonebotpy-bot
    depends_on:
      - db

  db:
    image: mongo
    container_name: timezonebotpy-db
    ports:
      - 27017:27017
    volumes:
      - /var/lib/mongodb:/data/db